//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPioneers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public int Id { get; set; }
        public string AnswerBody { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
        public Nullable<int> AnsweredBy { get; set; }
        public int QuestionId { get; set; }
        public byte[] Attachment { get; set; }
        public byte[] Snapshot { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
    }
}
