//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPioneers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.ITEMS = new HashSet<ITEM>();
            this.SETUP_PACKAGES = new HashSet<SETUP_PACKAGES>();
            this.SETUP_SCREENS = new HashSet<SETUP_SCREENS>();
            this.SETUP_SCREENS1 = new HashSet<SETUP_SCREENS>();
            this.USER_DEFINTIONS = new HashSet<USER_DEFINTIONS>();
            this.USER_GROUPS = new HashSet<USER_GROUPS>();
            this.USER_SECURITY_LIST = new HashSet<USER_SECURITY_LIST>();
        }
    
        public int ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public bool ACTIVE_IND { get; set; }
    
        public virtual ICollection<ITEM> ITEMS { get; set; }
        public virtual ICollection<SETUP_PACKAGES> SETUP_PACKAGES { get; set; }
        public virtual ICollection<SETUP_SCREENS> SETUP_SCREENS { get; set; }
        public virtual ICollection<SETUP_SCREENS> SETUP_SCREENS1 { get; set; }
        public virtual ICollection<USER_DEFINTIONS> USER_DEFINTIONS { get; set; }
        public virtual ICollection<USER_GROUPS> USER_GROUPS { get; set; }
        public virtual ICollection<USER_SECURITY_LIST> USER_SECURITY_LIST { get; set; }
    }
}
