//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPioneers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevPEntities : DbContext
    {
        public DevPEntities()
            : base("name=DevPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANSWER> ANSWERS { get; set; }
        public DbSet<COMPANY> COMPANies { get; set; }
        public DbSet<ITEM> ITEMS { get; set; }
        public DbSet<QUESTION> QUESTIONS { get; set; }
        public DbSet<SETUP_PACKAGES> SETUP_PACKAGES { get; set; }
        public DbSet<SETUP_PRODUCTS> SETUP_PRODUCTS { get; set; }
        public DbSet<SETUP_SCREENS> SETUP_SCREENS { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<USER_DEFINTIONS> USER_DEFINTIONS { get; set; }
        public DbSet<USER_GROUPS> USER_GROUPS { get; set; }
        public DbSet<USER_SECURITY_LIST> USER_SECURITY_LIST { get; set; }
        public DbSet<USER_SUBSCRIPTION> USER_SUBSCRIPTION { get; set; }
        public DbSet<USER_TRANSACTIONS> USER_TRANSACTIONS { get; set; }
    }
}
