//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPioneers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public int Id { get; set; }
        public string QuestionTitle { get; set; }
        public string QuestionBody { get; set; }
        public Nullable<System.DateTime> AskedDate { get; set; }
        public int AskedBy { get; set; }
        public byte[] Attachment { get; set; }
        public byte[] Snapshot { get; set; }
    
        public virtual ANSWER ANSWER { get; set; }
    }
}
