//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPioneers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_SCREENS
    {
        public int ID { get; set; }
        public string SCREEN_NAME { get; set; }
        public bool ACTIVE_IND { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual COMPANY COMPANY1 { get; set; }
    }
}
