//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPioneers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SUBSCRIPTION
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int PACKAGE_ID { get; set; }
        public Nullable<System.DateTime> ACTIVATION_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public bool ACTIVE_IND { get; set; }
    }
}
