//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPioneers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SECURITY_LIST
    {
        public int ID { get; set; }
        public string ITEM_NAME { get; set; }
        public string SCREEN_NAME { get; set; }
        public int USER_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual USER_DEFINTIONS USER_DEFINTIONS { get; set; }
    }
}
